### ISSUE TITLE
More than one player ended with the same score

### ISSUE THREAD

**Issue by sepandhaghighi** [sepandhaghighi/penney#12]
#### Description
When more than one player ended with the same score
#### Expected Behavior
Tie or more than one winner!!
#### Actual Behavior
![penney-bug](https://user-images.githubusercontent.com/7515099/78908611-9663e180-7a97-11ea-9147-052e7e14764a.png)
#### Operating System
Windows 10
#### Python Version
Python 3.6
#### Penney Version (Use : `penney.__version__`)
`Penney 0.2`

**Comment by sepandhaghighi** [comment]
@sadrasabouri Whats your idea about this bug ? 
Tie or more than one winner ?!?

**Comment by sadrasabouri** [comment]
I think as we're showing the results the term "tie" is more proper.
But we can write down a list of winners instead, if this list's length's equal to players number so the game is tie.
